export const ROLE_UI = {
  super_admin: {
    roleKey: 'super_admin',
    roleLabel: 'Super Admin',
    panelLabel: 'Platform Control',
    homePath: '/super-admin/dashboard',
    navItems: [
      { label: 'Dashboard', to: '/super-admin/dashboard', icon: 'SA' },
      { label: 'Stores', to: '/super-admin/stores', icon: 'ST' },
    ],
    permissions: [
      'Monitor all CrystalBubble stores',
      'Onboard stores and first administrators',
      'Suspend or reactivate store access',
    ],
  },
  admin: {
    roleKey: 'admin',
    roleLabel: 'Administrator',
    panelLabel: 'Admin Control Center',
    homePath: '/admin/dashboard',
    navItems: [
      { label: 'Dashboard', to: '/admin/dashboard', icon: 'DB' },
      { label: 'Manage Customers', to: '/admin/manage-customers', icon: 'CU' },
      { label: 'Manage Staff', to: '/admin/manage-staff', icon: 'ST' },
      { label: 'Orders', to: '/admin/orders', icon: 'OR' },
      { label: 'Order Tracking', to: '/admin/order-tracking', icon: 'TR' },
      { label: 'Pickup Scheduling', to: '/admin/pickup-scheduling', icon: 'PU' },
      { label: 'Messaging', to: '/admin/messaging', icon: 'MS' },
      { label: 'Sales', to: '/admin/sales', icon: 'SA' },
      { label: 'Expenses', to: '/admin/expenses', icon: 'EX' },
      { label: 'Official Receipt', to: '/admin/official-receipt', icon: 'OR' },
      { label: 'Consolidated Report', to: '/admin/consolidated-report', icon: 'CR' },
      { label: 'Inventory', to: '/admin/inventory', icon: 'IN' },
    ],
    permissions: [
      'Full customer and staff accounts',
      'Financial reports, payments, and consolidated reporting',
      'System-wide order tracking and inventory control',
    ],
  },
  staff: {
    roleKey: 'staff',
    roleLabel: 'Staff',
    panelLabel: 'Operations Workspace',
    homePath: '/staff/dashboard',
    navItems: [
      { label: 'Dashboard', to: '/staff/dashboard', icon: 'DB' },
      { label: 'Customers', to: '/staff/customers', icon: 'CU' },
      { label: 'Orders', to: '/staff/orders', icon: 'OR' },
      { label: 'Pickup Scheduling', to: '/staff/pickup-scheduling', icon: 'PU' },
      { label: 'Inventory', to: '/staff/inventory', icon: 'IN' },
      { label: 'Assigned Orders', to: '/staff/assigned-orders', icon: 'AO' },
      { label: 'Laundry Queue', to: '/staff/laundry-queue', icon: 'LQ' },
      { label: 'Release Orders', to: '/staff/release-orders', icon: 'RO' },
      { label: 'Official Receipt', to: '/staff/official-receipt', icon: 'OR' },
      { label: 'Messaging', to: '/staff/messaging', icon: 'MS' },
    ],
    permissions: [
      'Shared operational modules: customers, orders, pickup, inventory, messaging',
      'Daily production: assigned work, queue, and customer releases',
      'No staff management, financial reports, or full system administration',
    ],
  },
  customer: {
    roleKey: 'customer',
    roleLabel: 'Customer',
    panelLabel: 'Customer Portal',
    homePath: '/customer/dashboard',
    navItems: [
      { label: 'Dashboard', to: '/customer/dashboard', icon: 'DB' },
      { label: 'New Order', to: '/customer/new-order', icon: 'NO' },
      { label: 'My Orders', to: '/customer/my-orders', icon: 'MO' },
      { label: 'Messaging', to: '/customer/messaging', icon: 'MS' },
      { label: 'Track Orders', to: '/customer/track-orders', icon: 'TO' },
      { label: 'Payments', to: '/customer/payments', icon: 'PM' },
      { label: 'Order History', to: '/customer/order-history', icon: 'OH' },
    ],
    permissions: ['Create and track personal orders', 'View personal payments and history', 'Manage personal preferences only'],
  },
}
